version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx1600m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "quickstart/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "quickstart/build.gradle" }}
      - run:
          name: Run build
          command: ./gradlew assembleRelease assembleDebug
      - store_artifacts:
          path: quickstart/build/outputs
          destination: reports
      # - store_test_results:
      #     path: quickstart/build/test-results
