name: Build

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGES.md'
      - 'LICENSE'
      - 'THANKS'

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
      - name: Copy gradle.properties
        run: cp gradle.properties.example gradle.properties
      - name: Build with Gradle
        run: ./gradlew build
      - name: Lint Check
        run: ./gradlew ktlintCheck
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: sora-android-sdk
          SLACK_COLOR: danger
          SLACK_TITLE: Build failed
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
